### ISSUE TITLE
Uninstall leftover 

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny4OTRS-SortByLastContact#8]
![image](https://cloud.githubusercontent.com/assets/378324/12866692/bb8c536a-ccd7-11e5-8999-4bca01d8106a.png)

After uninstalling the addon it is not possible to remove the dynamic fields which are created during installation. Is it possible to remove the internal flag of the dynamic field when on uninstall?

**Comment by thorsteneckel** [comment]
Hi @hypericum - please have a look at this. Thanks!

**Comment by hypericum** [comment]
@rkaldung unfortunately DynamicFieldUpdate (Framwork function for changing DynamicFields) can't change the internal flag. 

Solution is to create the dynamic fields as non-internal fields. Code has been updated, demo can be found on vz690. Please QA and if ok trigger me for a new version or build it by yourself. *thx*

**Comment by rkaldung** [comment]
Since the data stored in the dynamic field can be restored by running the bin scripts I recommend removing the data on uninstall, maybe with a little hint. Don't setting the field internal could lead to more problems when a user still remove the dynamic field. 
@thorsteneckel Do you agree?

**Comment by thorsteneckel** [comment]
I totally agree wir @rkaldung . After uninstalling the package the stored data is useless since it's inconsistent and misleading after the first incoming customer contact. We should remove it. Please do so @hypericum and switch to Code* blocks in the SOPM as written in the new issue https://github.com/znuny/Znuny4OTRS-SortByLastContact/issues/9 I created.
